### ISSUE TITLE
Error at sharedWithInstanceToken

### ISSUE THREAD

**Issue by phuongpt** [projetoeureka/react-native-mixpanel-bridge#1]
Thank for this plugin 👍 
I installed successfully on iOS, but got
```
_reactNativeMixpanelBridge2.default.sharedWithInstanceToken is not a function
```
when init run `Mixpanel.sharedWithInstanceToken(mixPanelToken)`. Can you help to check?
I'm using RN 0.41.0

**Comment by msefidi** [comment]
he has mentioned that it does not work on version > 0.40.0
```
It's known it doesn't work with versions >= 0.40.0 due 
to changes on location of React Native headers.
```

**Comment by phuongpt** [comment]
ah sorry my mistake :(

**Comment by duailibe** [comment]
Yeah, this was made for an internal project that uses RN 0.36.0, so we have no plans to support RN >= 0.40.0 yet. You're welcome to submit a PR if you have the time!

Thanks

**Comment by nateReiners** [comment]
This was actually working fine for us on RN 0.51.0, but only now when upgrading to RN 56 do I see this error. @duailibe, Are you telling me that this package is basically not intended for use with RN > 40?
